### PR TITLE
Last bit of fixes before 2.0 release

### LINKED ISSUE #161: Error on macos: Project file not found at
It seems that the different slashes confuse it:

```
csproj-to-2017 ./cryptoportfolio.sln 
Solution parsing started.
Project found: cryptoportfolio\cryptoportfolio.csproj
Project file not found at: /Users/rob/Dropbox/src/cryptoportfolio/cryptoportfolio\cryptoportfolio.csproj

```
Project file is there, but it should use path /Users/rob/Dropbox/src/cryptoportfolio/cryptoportfolio/cryptoportfolio.csproj

In the SLN the proj is defined as 
`Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "cryptoportfolio", "cryptoportfolio\cryptoportfolio.csproj", "{3C579E5C-ABF9-4286-AAF3-8230FB37BEB7}"
`

### PR DESCRIPTION
**Pull request by andrew-boyarshin**
* API removal: Remove `RootNamespace` and `AssemblyName` properties from model (it was RC right? one tiny change)
* Extended `ProjectReference` model (and added filling new properties to both `SolutionReader` and `ProjectReader`)
* Use new APIs in diagnostics W001, W010, W034
* Fix AssemblyInfo detection when file is missing (e.g. generated during build from template)
* Extend `ConditionEvaluator` APIs to allow more efficient queries
* Recreate relative path fix set for Unix-like OS closely based on MSBuild sources (works only on non-Windows platforms)
* Rewrite `SolutionReader` to use MSBuild routine for parsing _Project_ definition lines
* Add `EmptyGroupRemoveTransformation` (obvious designation, fixes regression in one of my latest PRs)
* Greatly improve property simplification per issue #165
* Fix regression in one of my latest PRs: applying full set of transformations on CPS projects. Sigh.
* Adapt tests to changes

Closes #161.

### CODE REVIEW

File: Project2015To2017/Reading/ProjectPropertiesReader.cs [hunk 1]
```diff
@@ -145,7 +142,7 @@ string[] ParseFromProperty(string name) => project.Property(name)
 				.Split(new[] {';'}, StringSplitOptions.RemoveEmptyEntries);
 		}
 
-		private static void ReadPropertyGroups(Project project)
+		internal static void ReadPropertyGroups(Project project)
```
Comment (andrew-boyarshin) [inline Project2015To2017/Reading/ProjectPropertiesReader.cs]: For accessibility in tests.

File: Project2015To2017/Reading/SolutionReader.cs [hunk 2]
```diff
@@ -11,35 +11,74 @@ public sealed class SolutionReader
 	{
 		public static readonly SolutionReader Instance = new SolutionReader();
 
+		// An example of a project line looks like this:
+		//  Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ClassLibrary1", "ClassLibrary1\ClassLibrary1.csproj", "{05A5AD00-71B5-4612-AF2F-9EA9121C4111}"
+		private static readonly Lazy<Regex> crackProjectLine = new Lazy<Regex>(
```
Comment (andrew-boyarshin) [inline Project2015To2017/Reading/SolutionReader.cs]: I still believe `Lazy` is a good idea. The overhead is actually small (I looked at `Lazy` sources), but improves cases when there is no need to **compile** heavy Regex, like when only projects are specified.

File: Project2015To2017/ProjectConverter.cs [hunk 3]
```diff
@@ -18,13 +18,24 @@ public sealed class ProjectConverter
...
 		{
+			var targetFrameworkTransformation = new TargetFrameworkTransformation(
+				conversionOptions.TargetFrameworks,
+				conversionOptions.AppendTargetFrameworkToOutputPath);
+
+			if (modernProject)
+			{
+				return new ITransformation[]
+				{
+					targetFrameworkTransformation
```
Comment (mungojam) [inline Project2015To2017/ProjectConverter.cs]: Could we keep some of the other transforms? They might apply if somebody had used an older version of the converter that didn't have all of the current simplifications. Not needed for this release though

File: Project2015To2017/Reading/SolutionReader.cs (hunk 2 above)
Comment (mungojam) [reply Project2015To2017/Reading/SolutionReader.cs]: I think in those cases it won't ever initialise SolutionReader including the static fields, but could be wrong

File: Project2015To2017/Reading/SolutionReader.cs [hunk 4]
```diff
@@ -11,35 +11,74 @@ public sealed class SolutionReader
...
+				+ "\"(?<RELATIVEPATH>.*)\""
+				+ "\\s*,\\s*" // Any amount of whitespace plus "," plus any amount of whitespace
+				+ "\"(?<PROJECTGUID>.*)\""
+				+ "$", // End-of-line
+				RegexOptions.Compiled
+			)
+		);
+
+		private const string vbProjectGuid = "{F184B08F-C81C-45F6-A57F-5ABD9991F28F}";
+		private const string csProjectGuid = "{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}";
```
Comment (mungojam) [inline Project2015To2017/Reading/SolutionReader.cs]: are you sure this covers all generations of Visual Studio and things like test projects? What about WPF? I had a feeling that there were more possible values it could take.

File: Project2015To2017/Transforms/EmptyGroupRemoveTransformation.cs [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+		public void Transform(Project definition, ILogger logger)
+		{
+			definition.PropertyGroups = FilterNonEmpty(definition.PropertyGroups);
+			definition.ItemGroups = FilterNonEmpty(definition.ItemGroups).ToList();
+		}
+
+		private static IReadOnlyList<XElement> FilterNonEmpty(IEnumerable<XElement> groups)
+		{
+			var (keep, remove) = groups
+				.Split(x => x.HasElements
```
Comment (mungojam) [inline Project2015To2017/Transforms/EmptyGroupRemoveTransformation.cs]: Do you need to filter out comments here too? Here's an example from the current converter which produces [this csproj](https://github.com/mungojam/Force.com-Toolkit-for-NET/blob/with-pr-167/src/ForceToolkitForNET/ForceToolkitForNET.csproj) with:
```xml
  <ItemGroup>
    <!-- A reference to the entire .NET Framework is automatically included -->
  </ItemGroup>
```

File: Project2015To2017/Transforms/NuGetPackageTransformation.cs [hunk 6]
```diff
@@ -76,10 +77,8 @@ private string PopulatePlaceHolder(string placeHolder, string nuSpecValue, strin
 			{
 				return assemblyAttributeValue ?? nuSpecValue;
 			}
-			else
-			{
-				return nuSpecValue;
-			}
+
+			return nuSpecValue;
```
Comment (mungojam) [inline Project2015To2017/Transforms/NuGetPackageTransformation.cs]: I guess we have different styles here. This is one resharper warning we disable at work because we prefer the clarity of if/else

**Comment by mungojam** [comment]
The new solution parser is great, but it's getting confused by solution folders. I ran it against [this solution](https://github.com/mungojam/Force.com-Toolkit-for-NET/blob/with-stripped-projects/src/ForceToolkitForNET.sln) and it warned about the two solution folders:

> warn Unsupported project[Tests] type {2150E333-8FDC-42A3-9474-1A3956D46DE8}
warn Unsupported project[.nuget] type {2150E333-8FDC-42A3-9474-1A3956D46DE8}

File: Project2015To2017/Transforms/EmptyGroupRemoveTransformation.cs (hunk 5 above)
Comment (mungojam) [reply Project2015To2017/Transforms/EmptyGroupRemoveTransformation.cs]: Actually, it's [not happening anymore](https://github.com/mungojam/Force.com-Toolkit-for-NET/blob/rc-fixes/src/ForceToolkitForNET/ForceToolkitForNET.csproj) so probably fine

File: Project2015To2017/Reading/ProjectReader.cs [hunk 7]
```diff
@@ -150,13 +150,21 @@ private static void ProcessProjectReferences(Project projectDefinition)
...
+				var projectDirectory = projectDefinition.FilePath.DirectoryName;
+				var adjustedPath = Extensions.MaybeAdjustFilePath(path, projectDirectory);
+				reference.ProjectFile = new FileInfo(Path.Combine(projectDirectory, adjustedPath));
 			}
 		}
 
 		private FileInfo FindPackagesConfigFile(FileInfo projectFile)
 		{
-			var packagesConfig = new FileInfo(Path.Combine(projectFile.Directory.FullName, "packages.config"));
+			var packagesConfig = new FileInfo(Path.Combine(projectFile.DirectoryName, "packages.config"));
```
Comment (hvanbakel) [inline Project2015To2017/Reading/ProjectReader.cs]: This doesn't work if your directory is nested, right? Fullname took the entire path, this makes the assumption of being one folder deep?

File: Project2015To2017/Reading/SolutionReader.cs (hunk 2 above)
Comment (andrew-boyarshin) [reply Project2015To2017/Reading/SolutionReader.cs]: I'm afraid we can't guarantee that. The first time `Instance` or any other field is accessed, all static fields are initialized. Imagine we add sometime later a new static field to SolutionReader and access that in ProjectConverter unconditionally, then regex will always be initialized and compiled. MSBuild folks didn't do it out of pure will to have _perfect_ code.

File: Project2015To2017/ProjectConverter.cs (hunk 3 above)
Comment (andrew-boyarshin) [reply Project2015To2017/ProjectConverter.cs]: That's a matter for different PR. We shouldn't change CPS project files at all when we read and write them, unless any additional transformations are passed in `ConversionOptions`.

File: Project2015To2017/Reading/SolutionReader.cs (hunk 4 above)
Comment (andrew-boyarshin) [reply Project2015To2017/Reading/SolutionReader.cs]: These are not the ProjectTypeGuids from project file. These are specific solution Guids, that cover all managed languages supported by latest MSBuild but J# and C++/CLI. This was taken directly from MSBuild sources.

File: Project2015To2017/Reading/ProjectReader.cs (hunk 7 above)
Comment (andrew-boyarshin) [reply Project2015To2017/Reading/ProjectReader.cs]: I'm afraid it's incorrect. [DirectoryName reference](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo.directoryname?redirectedfrom=MSDN&view=netframework-4.7.2#System_IO_FileInfo_DirectoryName).
`Directory` property internally calls `DirectoryName`, checks `string.IsNullOrEmpty`, and creates `DirectoryInfo` instance from that string.

**Comment by andrew-boyarshin** [comment]
@hvanbakel please, reconsider your review decision taking my comments in consideration.

**Comment by andrew-boyarshin** [comment]
@mungojam it doesn't get confused by folder, it just outputs warning and ignores this "folder" project. Maybe we indeed could ignore warning for the respective TypeGuid.

File: Project2015To2017/Reading/ProjectReader.cs (hunk 7 above)
Comment (hvanbakel) [reply Project2015To2017/Reading/ProjectReader.cs]: Interesting, you’re right I was thinking of `DirectoryInfo.Name`

**Comment by mungojam** [comment]
> Maybe we indeed could ignore warning for the respective TypeGuid

Yes please let's do that. Current behaviour is confusing
